# Generated by Django 2.1.3 on 2018-12-06 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matiere', models.CharField(max_length=20)),
                ('note', models.IntegerField()),
                ('coefficient', models.DecimalField(decimal_places=2, max_digits=2)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_app.Student')),
            ],
        ),
    ]
